In [1]:
import pandas as pd
import numpy as np

In [7]:
data = pd.read_csv(
    'C:/Users/Neslihan Seker/Desktop/Data-Analysis-Projects/Handling Missing Values/Building_Permits.csv',
    low_memory=False
)

In [8]:
data.head()

,Permit Number,Permit Type,Permit Type Definition,Permit Creation Date,Block,Lot,Street Number,Street Number Suffix,Street Name,Street Suffix,...,Existing Construction Type,Existing Construction Type Description,Proposed Construction Type,Proposed Construction Type Description,Site Permit,Supervisor District,Neighborhoods - Analysis Boundaries,Zipcode,Location,Record ID
0,201505065519,4,sign - erect,05/06/2015,0326,023,140,NaN,Ellis,St,...,3.0,constr type 3,NaN,NaN,NaN,3.0,Tenderloin,94102.0,"(37.785719256680785, -122.40852313194863)",1380611233945
1,201604195146,4,sign - erect,04/19/2016,0306,007,440,NaN,Geary,St,...,3.0,constr type 3,NaN,NaN,NaN,3.0,Tenderloin,94102.0,"(37.78733980600732, -122.41063199757738)",1420164406718
2,201605278609,3,additions alterations or repairs,05/27/2016,0595,203,1647,NaN,Pacific,Av,...,1.0,constr type 1,1.0,constr type 1,NaN,3.0,Russian Hill,94109.0,"(37.7946573324287, -122.42232562979227)",1424856504716
3,201611072166,8,otc alterations permit,11/07/2016,0156,011,1230,NaN,Pacific,Av,...,5.0,wood frame (5),5.0,wood frame (5),NaN,3.0,Nob Hill,94109.0,"(37.79595867909168, -122.41557405519474)",1443574295566
4,201611283529,6,demolitions,11/28/2016,0342,001,950,NaN,Market,St,...,3.0,constr type 3,NaN,NaN,NaN,6.0,Tenderloin,94102.0,"(37.78315261897309, -122.40950883997789)",144548169992

In [9]:
missing_values = data.isnull().sum()
missing_values[0:10]

Permit Number                  0
Permit Type                    0
Permit Type Definition         0
Permit Creation Date           0
Block                          0
Lot                            0
Street Number                  0
Street Number Suffix      196684
Street Name                    0
Street Suffix               2768
dtype: int64

In [10]:
total_cells = np.product(data.shape)
total_missing = missing_values.sum()

(total_missing/total_cells)*100

26.26002315058403

In [17]:
missing_values[0:10]

Permit Number                  0
Permit Type                    0
Permit Type Definition         0
Permit Creation Date           0
Block                          0
Lot                            0
Street Number                  0
Street Number Suffix      196684
Street Name                    0
Street Suffix               2768
dtype: int64

In [14]:
data.sample(5)

,Permit Number,Permit Type,Permit Type Definition,Permit Creation Date,Block,Lot,Street Number,Street Number Suffix,Street Name,Street Suffix,...,Existing Construction Type,Existing Construction Type Description,Proposed Construction Type,Proposed Construction Type Description,Site Permit,Supervisor District,Neighborhoods - Analysis Boundaries,Zipcode,Location,Record ID
107085,M640547,8,otc alterations permit,11/24/2015,1413,005,229,NaN,20th,Av,...,NaN,NaN,NaN,NaN,NaN,1.0,Outer Richmond,94121.0,"(37.78355875125357, -122.4799410869351)",140454298671
79987,M572167,8,otc alterations permit,03/24/2015,1176,011,1640,NaN,Fulton,St,...,NaN,NaN,NaN,NaN,NaN,5.0,Lone Mountain/USF,94117.0,"(37.77642056410579, -122.44388325275195)",137547091366
93473,201507282623,8,otc alterations permit,07/28/2015,6685,007,242,NaN,Chenery,St,...,5.0,wood frame (5),5.0,wood frame (5),NaN,8.0,Glen Park,94131.0,"(37.73826516328148, -122.42659317651896)",1389914210559
125816,201605318738,8,otc alterations permit,05/31/2016,3581,087,498,NaN,Sanchez,St,...,5.0,wood frame (5),5.0,wood frame (5),NaN,8.0,Castro/Upper Market,94114.0,"(37.76126148812797, -122.43084675048941)",1425052360488
45485,201404213693,8,otc alterations permit,04/21/2014,0436D,043,3732,NaN,Fillmore,St,...,5.0,wood frame (5),5.0,wood frame (5),NaN,2.0,Marina,94123.0,"(37.805116463419886, -122.43681582493232)",1339251392467

In [19]:
data['Zipcode'].isnull().sum()

1716

In [20]:
drop_columns = data.dropna(axis=1)
drop_columns.head(5)

,Permit Number,Permit Type,Permit Type Definition,Permit Creation Date,Block,Lot,Street Number,Street Name,Current Status,Current Status Date,Filed Date,Record ID
0,201505065519,4,sign - erect,05/06/2015,0326,023,140,Ellis,expired,12/21/2017,05/06/2015,1380611233945
1,201604195146,4,sign - erect,04/19/2016,0306,007,440,Geary,issued,08/03/2017,04/19/2016,1420164406718
2,201605278609,3,additions alterations or repairs,05/27/2016,0595,203,1647,Pacific,withdrawn,09/26/2017,05/27/2016,1424856504716
3,201611072166,8,otc alterations permit,11/07/2016,0156,011,1230,Pacific,complete,07/24/2017,11/07/2016,1443574295566
4,201611283529,6,demolitions,11/28/2016,0342,001,950,Market,issued,12/01/2017,11/28/2016,144548169992

In [22]:
print('Columns in original dataset: %d \n' %data.shape [1] )
print('Columns are dropped: %d \n' %drop_columns.shape [1] )

Columns in original dataset: 43

Columns are dropped: 12

In [26]:
subset_data = data.loc[:, 'Permit Type':'Street Suffix'].head()
subset_data

,Permit Type,Permit Type Definition,Permit Creation Date,Block,Lot,Street Number,Street Number Suffix,Street Name,Street Suffix
0,4,sign - erect,05/06/2015,0326,023,140,NaN,Ellis,St
1,4,sign - erect,04/19/2016,0306,007,440,NaN,Geary,St
2,3,additions alterations or repairs,05/27/2016,0595,203,1647,NaN,Pacific,Av
3,8,otc alterations permit,11/07/2016,0156,011,1230,NaN,Pacific,Av
4,6,demolitions,11/28/2016,0342,001,950,NaN,Market,St

In [27]:
subset_data.isnull().sum()

Permit Type               0
Permit Type Definition    0
Permit Creation Date      0
Block                     0
Lot                       0
Street Number             0
Street Number Suffix      5
Street Name               0
Street Suffix             0
dtype: int64

In [28]:
subset_data.fillna(0)

C:\Users\Neslihan Seker\AppData\Local\Temp\ipykernel_9460\1473254981.py:1: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  subset_data.fillna(0)

,Permit Type,Permit Type Definition,Permit Creation Date,Block,Lot,Street Number,Street Number Suffix,Street Name,Street Suffix
0,4,sign - erect,05/06/2015,0326,023,140,0,Ellis,St
1,4,sign - erect,04/19/2016,0306,007,440,0,Geary,St
2,3,additions alterations or repairs,05/27/2016,0595,203,1647,0,Pacific,Av
3,8,otc alterations permit,11/07/2016,0156,011,1230,0,Pacific,Av
4,6,demolitions,11/28/2016,0342,001,950,0,Market,St

In [30]:
subset_data.fillna(method='bfill', axis=0).fillna(0)

C:\Users\Neslihan Seker\AppData\Local\Temp\ipykernel_9460\1950032661.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  subset_data.fillna(method='bfill', axis=0).fillna(0)
C:\Users\Neslihan Seker\AppData\Local\Temp\ipykernel_9460\1950032661.py:1: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  subset_data.fillna(method='bfill', axis=0).fillna(0)

,Permit Type,Permit Type Definition,Permit Creation Date,Block,Lot,Street Number,Street Number Suffix,Street Name,Street Suffix
0,4,sign - erect,05/06/2015,0326,023,140,0.0,Ellis,St
1,4,sign - erect,04/19/2016,0306,007,440,0.0,Geary,St
2,3,additions alterations or repairs,05/27/2016,0595,203,1647,0.0,Pacific,Av
3,8,otc alterations permit,11/07/2016,0156,011,1230,0.0,Pacific,Av
4,6,demolitions,11/28/2016,0342,001,950,0.0,Market,St